(function(){
  var products={
    daily:[['1日間','500','eSIM-KR2G-01','KR2G-01'],['3日間','980','eSIM-KR2G-03','KR2G-03'],['5日間','1280','eSIM-KR2G-05','KR2G-05'],['7日間','1580','eSIM-KR2G-07','KR2G-07'],['10日間','2180','eSIM-KR2G-10','KR2G-10'],['15日間','2980','eSIM-KR2G-15','KR2G-15'],['20日間','3780','eSIM-KR2G-20','KR2G-20'],['30日間','4980','eSIM-KR2G-30','KR2G-30']],
    unlimited:[['1日間','700','eSIM-SKTUL-01','SKTUL-01'],['2日間','1050','eSIM-SKTUL-02','SKTUL-02'],['3日間','1450','eSIM-SKTUL-03','SKTUL-03'],['4日間','1750','eSIM-SKTUL-04','SKTUL-04'],['5日間','2050','eSIM-SKTUL-05','SKTUL-05'],['6日間','2450','eSIM-SKTUL-06','SKTUL-06'],['7日間','2680','eSIM-SKTUL-07','SKTUL-07'],['8日間','2980','eSIM-SKTUL-08','SKTUL-08'],['9日間','3180','eSIM-SKTUL-09','SKTUL-09'],['10日間','3480','eSIM-SKTUL-10','SKTUL-10'],['15日間','4480','eSIM-SKTUL-15','SKTUL-15'],['20日間','5480','eSIM-SKTUL-20','SKTUL-20'],['30日間','6480','eSIM-SKTUL-30','SKTUL-30'],['60日間','9980','eSIM-SKTUL-60','SKTUL-60'],['90日間','12980','eSIM-SKTUL-90','SKTUL-90']]
  };
  var kind='daily',list=document.querySelector('.korea-plans'),tabs=[].slice.call(document.querySelectorAll('.korea-tab')),labels=[].slice.call(document.querySelectorAll('.selected-plan')),prices=[].slice.call(document.querySelectorAll('.price')),note=document.querySelector('.price-note');
  var distinction=document.createElement('section');distinction.className='korea-plan-distinction';distinction.innerHTML='<div class="distinction-card distinction-roaming"><b>毎日2GB高速</b><strong>ローミング回線</strong><span>TikTok・ChatGPTはご利用いただけません</span></div><div class="distinction-card distinction-native"><b>SKT 無制限</b><strong>原生韓国IP</strong><span>TikTok・ChatGPTをご利用いただけます</span></div>';var proof=document.querySelector('.proof-strip');if(proof)proof.parentNode.insertBefore(distinction,proof);
  function select(button){[].slice.call(list.querySelectorAll('.plan')).forEach(function(item){var active=item===button;item.classList.toggle('is-selected',active);item.setAttribute('aria-checked',active?'true':'false');});labels.forEach(function(item){item.textContent=button.dataset.plan;});prices.forEach(function(item){item.textContent='¥'+Number(button.dataset.price).toLocaleString('ja-JP');});if(note)note.textContent=kind==='daily'?'ローミング回線｜TikTok・ChatGPTは利用不可｜毎日2GB高速・超過後128kbps':'原生韓国IP（SKT）｜TikTok・ChatGPT利用可｜高速無制限';}
  function render(){list.innerHTML='';products[kind].forEach(function(item,index){var button=document.createElement('button');button.className='plan'+(index===0?' is-selected':'');button.type='button';button.setAttribute('role','radio');button.setAttribute('aria-checked',index===0?'true':'false');button.dataset.plan=item[0]+' '+(kind==='daily'?'2GB':'無制限');button.dataset.price=item[1];button.dataset.variant=item[2];button.dataset.sku=item[3];var isHot=item[0]==='3日間'||item[0]==='5日間';button.innerHTML='<strong>'+item[0]+'</strong><span>'+(kind==='daily'?'2GB高速':'無制限')+'</span>'+(isHot?'<em class="promo-label">人気</em>':'')+(index===0&&!isHot?'<em>おすすめ</em>':'');button.addEventListener('click',function(){select(button);});list.appendChild(button);});select(list.querySelector('.plan'));}
  tabs.forEach(function(tab){tab.addEventListener('click',function(){kind=tab.dataset.product;tabs.forEach(function(item){item.classList.toggle('is-active',item===tab);});render();});});
  document.querySelectorAll('[data-buy]').forEach(function(button){button.addEventListener('click',function(){var selected=list.querySelector('.plan.is-selected');if(!selected)return;var params=new URLSearchParams({plan:selected.dataset.plan,price:selected.dataset.price,variant:selected.dataset.variant,sku:selected.dataset.sku});window.location.href='checkout.html?'+params.toString();});});
  render();
})();
