const crypto = require("node:crypto");
const fs = require("node:fs");
const http = require("node:http");
const path = require("node:path");

const root = __dirname;
const plans = { 7: { data: "40GB", amount: 1980 }, 15: { data: "80GB", amount: 2640 }, 30: { data: "120GB", amount: 3840 } };
const env = (name) => { const value = process.env[name]; if (!value) throw new Error(`Missing environment variable: ${name}`); return value; };
const allowedOrigins = new Set(["https://esim.easygosim.com", "https://easygosim.com", "https://www.easygosim.com", "https://easygosim.us", "http://localhost:3000", "http://127.0.0.1:3000"]);
const json = (res, status, body, requestOrigin = "") => {
  const origin = allowedOrigins.has(requestOrigin) ? requestOrigin : "https://esim.easygosim.com";
  res.writeHead(status, { "content-type": "application/json; charset=utf-8", "access-control-allow-origin": origin, "access-control-allow-headers": "content-type", "access-control-allow-methods": "POST, OPTIONS", "cache-control": "no-store" });
  res.end(JSON.stringify(body));
};
const orderNo = () => `EGS-JP-MY-${new Date().toISOString().slice(0, 10).replaceAll("-", "")}-${crypto.randomBytes(3).toString("hex").toUpperCase()}`;
async function airwallex(pathname, options = {}) { const response = await fetch(`${process.env.AIRWALLEX_API_BASE_URL || "https://api.airwallex.com"}${pathname}`, { ...options, headers: { "content-type": "application/json", ...(options.headers || {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data?.message || data?.error?.message || `Airwallex request failed (${response.status})`); return data; }
async function token() { const response = await fetch(`${process.env.AIRWALLEX_API_BASE_URL || "https://api.airwallex.com"}/api/v1/authentication/login`, { method: "POST", headers: { "content-type": "application/json", "x-client-id": env("AIRWALLEX_CLIENT_ID"), "x-api-key": env("AIRWALLEX_API_KEY") } }); const data = await response.json().catch(() => ({})); if (!response.ok || !data.token) throw new Error("Airwallex authentication failed"); return data.token; }
async function supabase(table, options = {}) { const key = env("SUPABASE_SERVICE_ROLE_KEY"); const response = await fetch(`${env("SUPABASE_URL")}/rest/v1/${table}`, { ...options, headers: { apikey: key, authorization: `Bearer ${key}`, "content-type": "application/json", ...(options.headers || {}) } }); const text = await response.text(); const data = text ? JSON.parse(text) : null; if (!response.ok) throw new Error(data?.message || data?.hint || `Supabase request failed (${response.status})`); return data; }
function readBody(req) { return new Promise((resolve, reject) => { let body = ""; req.on("data", (chunk) => { body += chunk; if (body.length > 100000) reject(new Error("Payload too large")); }); req.on("end", () => { try { resolve(body ? JSON.parse(body) : {}); } catch { reject(new Error("Invalid JSON")); } }); req.on("error", reject); }); }
async function createOrder(req, res) { try { const body = await readBody(req); const email = String(body.email || "").trim().toLowerCase() || null; const departure = String(body.departure_date || "").trim(); const days = Number(body.days); const plan = plans[days]; if (!plan || !/^\d{4}-\d{2}-\d{2}$/.test(departure)) return json(res, 400, { ok: false, error: "Invalid Malaysia plan or departure date" }); const no = orderNo(); const payment = await airwallex("/api/v1/pa/payment_links/create", { method: "POST", headers: { authorization: `Bearer ${await token()}` }, body: JSON.stringify({ amount: plan.amount, currency: "JPY", title: `Malaysia eSIM ${days} days - ${no}`, description: `${plan.data} Malaysia eSIM`, reference: no, reusable: false, collectable_shopper_info: { billing_address: false, message: false, phone_number: false, reference: false, shipping_address: false }, metadata: { order_no: no, product_key: "malaysia_manual", days: String(days), departure_date: departure, customer_email: email || "" } }) }); await supabase("jp_manual_orders", { method: "POST", headers: { prefer: "return=minimal" }, body: JSON.stringify({ order_no: no, product_key: "malaysia_manual", plan_days: days, data_allowance: plan.data, amount: plan.amount, currency: "JPY", customer_email: email, departure_date: departure, payment_status: "pending", fulfillment_status: "awaiting_payment", airwallex_payment_link_id: payment.id, airwallex_payment_url: payment.url }) }); return json(res, 200, { ok: true, order_no: no, payment_url: payment.url }); } catch (error) { console.error("JP manual order failed", error); return json(res, 500, { ok: false, error: "Unable to create payment" }); } }
function staticPath(urlPath) { const clean = urlPath.split("?")[0].replace(/\\/g, "/"); if (clean === "/blogs/news/2" || clean === "/blogs/news/2/") return "/blogs/news/2/index.html"; if (clean.startsWith("/products/")) return "/index.html"; if (clean === "/malaysia-esim-guide" || clean === "/malaysia-esim-guide/") return "/malaysia-esim-guide.html"; if (clean === "/checkout" || clean === "/checkout/") return "/checkout.html"; return clean === "/" ? "/index.html" : clean; }
const mime = { ".html": "text/html; charset=utf-8", ".js": "text/javascript; charset=utf-8", ".css": "text/css; charset=utf-8", ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".svg": "image/svg+xml", ".json": "application/json; charset=utf-8" };
const server = http.createServer(async (req, res) => { if (req.method === "OPTIONS" && req.url?.split("?")[0].startsWith("/api/")) return json(res, 204, {}, req.headers.origin || ""); if (req.method === "POST" && req.url?.split("?")[0] === "/api/create-order") return createOrder(req, res); if (req.method !== "GET") return res.writeHead(405).end(); const requested = staticPath(req.url || "/"); const file = path.resolve(root, "." + requested); if (!file.startsWith(root + path.sep) && file !== root) return res.writeHead(403).end("Forbidden"); fs.stat(file, (error, stat) => { if (error || !stat.isFile()) return res.writeHead(404, { "content-type": "text/plain; charset=utf-8" }).end("Not found"); res.writeHead(200, { "content-type": mime[path.extname(file).toLowerCase()] || "application/octet-stream" }); fs.createReadStream(file).pipe(res); }); });
server.listen(process.env.PORT || 8080, "0.0.0.0", () => console.log("EasyGoSim Japan server with payment API is ready"));
